### ISSUE TITLE
write nil with panic

### ISSUE THREAD

**Issue by tnclong** [theplant/prottp#5]
```
package prottp

import (
	"net/http/httptest"
	"testing"

	"github.com/gogo/protobuf/proto"
)

var writeMessageTestCases = []struct {
	name string

	isJson bool
	msg    proto.Message
}{
	{
		name: "nil of msg 1",

		isJson: true,
		msg:    nil,
	},
	{
		name: "nil of msg 2",

		isJson: false,
		msg:    nil,
	},
}

func TestWriteMessage(t *testing.T) {
	for _, tc := range writeMessageTestCases {
		res := httptest.NewRecorder()
		writeMessage(
			tc.isJson,
			tc.msg,
			res,
		)
	}
}

```

**Comment by tnclong** [comment]
The use cases:

`FindProductByCode(code string) (product *Product, err error)`
If we can't find products:
1. give a error and the product will be nil
2. both of product and err are nil

I do as `2`.

**Comment by tnclong** [comment]
I will try `1`.

**Comment by bodhi** [comment]
I was thinking you could use `oneof`, but if you do this:

> give a error and the product will be nil

~~I guess you could return a 404?~~

How will the client receive the error? 404 means "not found" but the service *was* found, it's just returning nothing.

**Comment by bodhi** [comment]
how about `repeated Product`? And say in the documentation it'll return zero or one, but not > 1?

**Comment by tnclong** [comment]
> how about repeated Product? And say in the documentation it'll return zero or one, but not > 1?

Thanks for your idea. 

I defined the `GetProductResponse`. Then let the `GetProductResponse` contains nil of product.

```
type GetProductResponse struct {
	Product *proto4.Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}
```

`return &GetProductResponse{}, nil`

**Comment by bodhi** [comment]
> protobuf:"bytes,1,opt,name=product"

`optional` is proto2. Are we using proto2 or proto3? For API clients, what will this look like in the protobuf service definition?

**Comment by tnclong** [comment]
The `opt` is auto generate by `protoc` in `syntax = "proto3"`

The Service in protobuf look like:
```
service ProductService {
  rpc GetProduct (GetProductParams) returns (GetProductResponse);
  rpc GetProducts (GetProductsParams) returns (GetProductsResponse);
}
```

**Comment by bodhi** [comment]
Ah, right, sorry. And the response looks like:

```
message GetProductsResponse {
  repeated Product products = 1;
}
```

Cool (except for awkward names!)
